name: filterpipeline
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - pytorch
  - bioconda
dependencies:
  - python==3.11.8
  - pytorch::faiss-gpu
  - pyarrow
  - pdbfixer
  - foldseek
  - mmseqs2
  - biotite
  - openbabel
  - openmm==8.3.1
  - fpocket
  - pip
  - plip
  - pip:
    - -e /disk1/ariane/vscode/enzyme-tk/
    - filterzyme
    - rdkit
    - freesasa
    - docko
    - chai_lab